/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DAOPhong;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Phong;

/**
 *
 * @author MSI
 */
public class viewPhong extends javax.swing.JFrame {

    private ArrayList<Phong> dsPhongs;
    DefaultTableModel model;
    /**
     * Creates new form viewPhong
     */
    public viewPhong() {
        initComponents();
        this.setLocationRelativeTo(null);
        dsPhongs = new DAOPhong().getListPhong();
        model = (DefaultTableModel) jTable1.getModel();
        showTable();
    }

    int i = 1;
    public void showTable () {
        for(Phong phong : dsPhongs){
            model.addRow(new Object[]{
                i++, phong.GetMaSoPhong(), phong.GetSoNguoiO(), phong.GetNgayBatDauThue()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnbacks = new javax.swing.JButton();
        jTextFieldThongBao = new javax.swing.JTextField();
        jTextFieldMaPhong = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNgayBatDauThue = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSoNguoiO = new javax.swing.JTextField();
        jButtonSuaPhong = new javax.swing.JButton();
        jButtonThemPhong = new javax.swing.JButton();
        jButtonXoaPhong = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel1.setText("Quản Lý Phòng");

        btnbacks.setBackground(new java.awt.Color(153, 255, 153));
        btnbacks.setText("Trở lại");
        btnbacks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbacksActionPerformed(evt);
            }
        });

        jTextFieldThongBao.setText("Thông báo : ");

        jLabel2.setText("Mã phòng :");

        jLabel3.setText("Ngày bắt đầu thuê  : ");

        jTextFieldNgayBatDauThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNgayBatDauThueActionPerformed(evt);
            }
        });

        jLabel5.setText("Số người ở : ");

        jTextFieldSoNguoiO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSoNguoiOActionPerformed(evt);
            }
        });

        jButtonSuaPhong.setBackground(new java.awt.Color(153, 255, 153));
        jButtonSuaPhong.setText("Sửa ");
        jButtonSuaPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaPhongActionPerformed(evt);
            }
        });

        jButtonThemPhong.setBackground(new java.awt.Color(153, 255, 153));
        jButtonThemPhong.setText("Thêm ");
        jButtonThemPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemPhongActionPerformed(evt);
            }
        });

        jButtonXoaPhong.setBackground(new java.awt.Color(153, 255, 153));
        jButtonXoaPhong.setText("Xóa");
        jButtonXoaPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaPhongActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã phòng", "Số người ở", "Ngày bắt đầu thuê"
            }
        ));
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnbacks, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jTextFieldThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jTextFieldNgayBatDauThue, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldSoNguoiO, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jButtonThemPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(jButtonSuaPhong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonXoaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnbacks)
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNgayBatDauThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldSoNguoiO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextFieldThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThemPhong)
                    .addComponent(jButtonSuaPhong)
                    .addComponent(jButtonXoaPhong))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSoNguoiOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSoNguoiOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSoNguoiOActionPerformed

    private void jTextFieldNgayBatDauThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNgayBatDauThueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNgayBatDauThueActionPerformed

    private void jButtonThemPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemPhongActionPerformed
        Phong phong = new Phong();
        phong.SetMaSoPhong(jTextFieldMaPhong.getText());
        phong.SetSoNguoiO(Integer.parseInt(jTextFieldSoNguoiO.getText()));
        try {
            phong.SetNgayBatDauThue(new SimpleDateFormat("dd-MM-yyyy").parse(jTextFieldNgayBatDauThue.getText())); 
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        dsPhongs.add(phong);
        if(new DAOPhong().ThemPhong(phong)){
            JOptionPane.showMessageDialog(rootPane, "Them thanh cong");
            dsPhongs.add(phong);
            showResult();
            jTextFieldThongBao.setText("Thông báo : Thêm thành công!");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Da ton tai ma nay");

        }
        jTextFieldMaPhong.setText("");
        jTextFieldNgayBatDauThue.setText("");
        jTextFieldSoNguoiO.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonThemPhongActionPerformed

    public void showResult() {
        Phong phong = dsPhongs.get(dsPhongs.size()-1);
        model.addRow(new Object[]{
            i++, phong.GetMaSoPhong(),phong.GetSoNguoiO(), phong.GetNgayBatDauThue()
        });
    }
    private void jButtonSuaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaPhongActionPerformed
        Phong phong = new Phong();
        phong.SetMaSoPhong(jTextFieldMaPhong.getText());
        phong.SetSoNguoiO(Integer.parseInt(jTextFieldSoNguoiO.getText())); 
        try {
            phong.SetNgayBatDauThue(new SimpleDateFormat("dd-MM-yyyy").parse(jTextFieldNgayBatDauThue.getText()));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        for (int j = 0; j < dsPhongs.size(); j++) {
            if(dsPhongs.get(j).GetMaSoPhong().equals(phong.GetMaSoPhong())){
                if(new DAOPhong().SuaPhong(phong)){
                    JOptionPane.showMessageDialog(rootPane, "Sua thanh cong");
                    Collections.replaceAll(dsPhongs, dsPhongs.get(j), phong);
                    showResult();
                    jTextFieldThongBao.setText("Thông báo : Sua thành công!");
                }else{
                     JOptionPane.showMessageDialog(rootPane, "Chua sua duoc");

                }
                dsPhongs.get(j).SetNgayBatDauThue(phong.GetNgayBatDauThue());
                dsPhongs.get(j).SetSoNguoiO(phong.GetSoNguoiO());
                model.removeRow(j);
                showResult();
                jTextFieldThongBao.setText("Thông báo : Sửa thành công");
            }else{
            }
        }
        jTextFieldMaPhong.setText("");
        jTextFieldNgayBatDauThue.setText("");
        jTextFieldSoNguoiO.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSuaPhongActionPerformed

    private void jButtonXoaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaPhongActionPerformed
        Phong phong = new Phong();
        phong.SetMaSoPhong( jTextFieldMaPhong.getText());
        for (int j = 0; j < dsPhongs.size(); j++) {
            if(dsPhongs.get(j).GetMaSoPhong().equals(phong.GetMaSoPhong())){
                if(new DAOPhong().XoaPhong(jTextFieldMaPhong.getText())){
                    JOptionPane.showMessageDialog(rootPane, "Xoa thanh cong");
                    dsPhongs.remove(dsPhongs.get(j));
                    showResult();
                    jTextFieldThongBao.setText("Thông báo : Xóa thành công!");
                }else{
                     JOptionPane.showMessageDialog(rootPane, "Chua xoa duoc");
                }
                model.removeRow(j);
            }else{
            }
        }
        jTextFieldMaPhong.setText("");
        jTextFieldNgayBatDauThue.setText("");
        jTextFieldSoNguoiO.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonXoaPhongActionPerformed

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1AncestorAdded

    private void btnbacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbacksActionPerformed
        this.hide();
        menu mn=new menu();
        mn.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbacksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewPhong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbacks;
    private javax.swing.JButton jButtonSuaPhong;
    private javax.swing.JButton jButtonThemPhong;
    private javax.swing.JButton jButtonXoaPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldMaPhong;
    private javax.swing.JTextField jTextFieldNgayBatDauThue;
    private javax.swing.JTextField jTextFieldSoNguoiO;
    private javax.swing.JTextField jTextFieldThongBao;
    // End of variables declaration//GEN-END:variables
}
