/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DAONguoiThue;
import controller.DAOPhong;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NguoiThue;
import model.Phong;

/**
 *
 * @author MSI
 */
public class viewNguoiThue extends javax.swing.JFrame {

    private  ArrayList<NguoiThue> dsNguoiThues;
    DefaultTableModel model;
    /**
     * Creates new form viewNguoiThue
     */
    public viewNguoiThue() {
        initComponents();
        this.setLocationRelativeTo(null);
        dsNguoiThues = new DAONguoiThue().getListNguoiThue();
        model = (DefaultTableModel) jTable1.getModel();
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextFieldThongBao = new javax.swing.JTextField();
        jButtonThem = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jTextFieldGioTinh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNgaySinh = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldDiaChi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldHoTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldMaSoPhong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMaNguoiThue = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnbacks = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setToolTipText("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã số phòng", "Mã người thuê", "Địa chỉ", "Họ tên", "Giới tính", "Ngày sinh"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextFieldThongBao.setText("Thông  báo : ");
        jTextFieldThongBao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldThongBaoActionPerformed(evt);
            }
        });

        jButtonThem.setBackground(new java.awt.Color(153, 255, 153));
        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });

        jButtonSua.setBackground(new java.awt.Color(153, 255, 153));
        jButtonSua.setText("Sửa");
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });

        jButtonXoa.setBackground(new java.awt.Color(153, 255, 153));
        jButtonXoa.setText("Xóa");
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });

        jLabel7.setText("Giới Tính");

        jLabel8.setText("Ngày Sinh");

        jLabel6.setText("Địa Chỉ");

        jLabel5.setText("Họ Tên");

        jLabel4.setText("Mã Số Phòng ");

        jLabel3.setText("Mã Người Thuê ");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Quản Lý Người Thuê");

        btnbacks.setBackground(new java.awt.Color(153, 255, 153));
        btnbacks.setText("Trở lại");
        btnbacks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbacksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jButtonThem)
                .addGap(184, 184, 184)
                .addComponent(jButtonSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonXoa)
                .addGap(130, 130, 130))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbacks, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jTextFieldMaSoPhong)
                                    .addComponent(jTextFieldGioTinh))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jTextFieldMaNguoiThue))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnbacks)
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldMaSoPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMaNguoiThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldGioTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSua)
                    .addComponent(jButtonXoa)
                    .addComponent(jButtonThem))
                .addGap(18, 18, 18)
                .addComponent(jTextFieldThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        // TODO add your handling code here:
        NguoiThue nguoiThue = new NguoiThue();
        nguoiThue.SetMaPhong(jTextFieldMaSoPhong.getText());
        nguoiThue.SetMaNguoiThue(jTextFieldMaNguoiThue.getText());
        nguoiThue.SetDiaChi(jTextFieldDiaChi.getText());
        nguoiThue.SetHoTen(jTextFieldHoTen.getText());
        nguoiThue.SetGioiTinh(jTextFieldGioTinh.getText());
        try {
            nguoiThue.SetNgaySinh(new SimpleDateFormat("dd-MM-yyyy").parse(jTextFieldNgaySinh.getText())); 
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        if(new DAONguoiThue().ThemNguoiThue(nguoiThue)){
            JOptionPane.showMessageDialog(rootPane, "Them thanh cong");
            dsNguoiThues.add(nguoiThue);
            showResult();
            jTextFieldThongBao.setText("Thông báo : Thêm thành công!");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Chua them duoc");

        }
        jTextFieldDiaChi.setText("");
        jTextFieldGioTinh.setText("");
        jTextFieldMaNguoiThue.setText("");
        jTextFieldHoTen.setText("");
        jTextFieldNgaySinh.setText("");
        jTextFieldMaSoPhong.setText("");
    }//GEN-LAST:event_jButtonThemActionPerformed

    public void showResult() {
        NguoiThue nguoiThue = dsNguoiThues.get(dsNguoiThues.size()-1);
        model.addRow(new Object[]{
            i++, nguoiThue.GetMaPhong(), nguoiThue.GetMaNguoiThue(), nguoiThue.GetDiaChi(), nguoiThue.GetHoTen(), nguoiThue.GetGioiTinh(), nguoiThue.GetNgaySinh()
        });
    }
    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
        NguoiThue nguoiThue = new NguoiThue();
        nguoiThue.SetMaNguoiThue(jTextFieldMaNguoiThue.getText());
        nguoiThue.SetHoTen(jTextFieldHoTen.getText());
        nguoiThue.SetMaPhong(jTextFieldMaSoPhong.getText());
        nguoiThue.SetDiaChi(jTextFieldDiaChi.getText());
        nguoiThue.SetGioiTinh(jTextFieldGioTinh.getText());
        try {
            nguoiThue.SetNgaySinh(new SimpleDateFormat("dd-MM-yyyy").parse(jTextFieldNgaySinh.getText()));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        for (int j = 0; j < dsNguoiThues.size(); j++) {
            if(dsNguoiThues.get(j).GetMaNguoiThue().equals(nguoiThue.GetMaNguoiThue())){
                if(new DAONguoiThue().SuaNguoiThue(nguoiThue)){
                    JOptionPane.showMessageDialog(rootPane, "Sua thanh cong");
                    Collections.replaceAll(dsNguoiThues, dsNguoiThues.get(j), nguoiThue);
                    showResult();
                    jTextFieldThongBao.setText("Thông báo : Sua thành công!");
                }else{
                     JOptionPane.showMessageDialog(rootPane, "Chua sua duoc");

                }
                dsNguoiThues.get(j).SetDiaChi(nguoiThue.GetDiaChi());
                dsNguoiThues.get(j).SetGioiTinh(nguoiThue.GetGioiTinh());
                dsNguoiThues.get(j).SetHoTen(nguoiThue.GetHoTen());
                dsNguoiThues.get(j).SetMaNguoiThue(nguoiThue.GetMaNguoiThue());
                dsNguoiThues.get(j).SetMaPhong(nguoiThue.GetMaPhong());
                dsNguoiThues.get(j).SetNgaySinh(nguoiThue.GetNgaySinh());
                model.removeRow(j);
                showResult();
                jTextFieldThongBao.setText("Thông báo : Sửa thành công");
            }else{
            }
        }
        jTextFieldDiaChi.setText("");
        jTextFieldGioTinh.setText("");
        jTextFieldHoTen.setText("");
        jTextFieldMaNguoiThue.setText("");
        jTextFieldMaSoPhong.setText("");
        jTextFieldNgaySinh.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
        // TODO add your handling code here:
        NguoiThue nguoiThue = new NguoiThue();
        nguoiThue.SetMaNguoiThue(jTextFieldMaNguoiThue.getText());
        for (int j = 0; j < dsNguoiThues.size(); j++) {
            if(dsNguoiThues.get(j).GetMaNguoiThue().equals(nguoiThue.GetMaNguoiThue())){
                if(new DAONguoiThue().XoaNguoiThue(jTextFieldMaNguoiThue.getText())){
                    JOptionPane.showMessageDialog(rootPane, "Xoa thanh cong");
                    dsNguoiThues.remove(dsNguoiThues.get(j));
                    model.removeRow(j);
                    jTextFieldThongBao.setText("Thông báo : Xoa thành công!");
                }else{
                     JOptionPane.showMessageDialog(rootPane, "Chua xoa duoc");
                }
            }else{
            }
        }
        jTextFieldDiaChi.setText("");
        jTextFieldGioTinh.setText("");
        jTextFieldHoTen.setText("");
        jTextFieldMaNguoiThue.setText("");
        jTextFieldMaSoPhong.setText("");
        jTextFieldNgaySinh.setText("");
    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void btnbacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbacksActionPerformed
        this.hide();
        menu mn=new menu();
        mn.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbacksActionPerformed

    private void jTextFieldThongBaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldThongBaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldThongBaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewNguoiThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewNguoiThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewNguoiThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewNguoiThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewNguoiThue().setVisible(true);
            }
        });
    }
    int i =1 ;
    public void showTable () {
        for(NguoiThue nguoiThue : dsNguoiThues){
            model.addRow(new Object[]{
                i++, nguoiThue.GetMaPhong(), nguoiThue.GetMaPhong(),nguoiThue.GetDiaChi(),nguoiThue.GetHoTen(), nguoiThue.GetGioiTinh(), nguoiThue.GetNgaySinh()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbacks;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldDiaChi;
    private javax.swing.JTextField jTextFieldGioTinh;
    private javax.swing.JTextField jTextFieldHoTen;
    private javax.swing.JTextField jTextFieldMaNguoiThue;
    private javax.swing.JTextField jTextFieldMaSoPhong;
    private javax.swing.JTextField jTextFieldNgaySinh;
    private javax.swing.JTextField jTextFieldThongBao;
    // End of variables declaration//GEN-END:variables
}
